title: Hypersonix
email: enquiries@hypersonix.space
description: > # this means to ignore newlines until "baseurl:"
  It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hypersonix.space" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
permalink: posts/:year/:month/:day/:title:output_ext